
require 'yaml'

configs = YAML.load_file('config.yaml')

MINIONNAME = configs['configs']['minionname']
SALTMASTER = configs['configs']['saltmaster']
PACKAGEURL = configs['configs']['packageurl']
MINIONFILE = configs['configs']['minionfile']
VBBOX = configs['configs']['vbbox']
USERNAME = configs['configs']['username']
PASSWORD = configs['configs']['password']


$script = <<SCRIPT
$minionname = $env:MinionName
$saltmaster = $env:SaltMaster
$packageurl = $env:PackageUrl
$minionfile = $env:MinionFile
mkdir c:\\stage\\
$filepath = "c:\\stage\\$minionfile"
$fileurl = "$packageurl$minionfile"
$webclient = New-Object System.Net.WebClient
$webclient.DownloadFile($fileurl, $filepath);
(new-object -com shell.application).shellexecute($filepath, "/S /master=$saltmaster /minion-name=$minionname");
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "#{VBBOX}"
  config.vm.box_check_update = false
  #config.vm.network "public_network", :adapter=>1
  config.vm.communicator = "winrm"

  config.vm.define "winbox" do |win|
    win.vm.hostname = "#{MINIONNAME}"
    win.vm.provider "virtualbox" do |v|
      v.gui = true
      v.name = "#{MINIONNAME}"
    end
  end

  config.winrm.username = "#{USERNAME}"
  config.winrm.password = "#{PASSWORD}"
  config.winrm.retry_limit = 20
  config.winrm.retry_delay = 10

  config.vm.provision "shell", inline: $script, env: {"MinionName" => MINIONNAME, "SaltMaster" => SALTMASTER, "MinionFile" => MINIONFILE, "PackageUrl" => PACKAGEURL}
end